package com.test.exceptionTest;

public class Test {
	
	public static void main(String[] args) {
		
	     
		   double x=5;
		   int y=0;
		   double z;
		  try{
		     
			  z=x/y;
		  
		  }catch (Exception e) {
			
			  System.out.println("出现异常啦....");
			  e.printStackTrace();
			  z=0;
		  }
		  
		  
		   System.out.println("z:"+z);
		   System.out.println("程序结束");
	}

}
